# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('mail', models.TextField()),
                ('fileName', models.TextField()),
                ('groupName', models.TextField()),
                ('sam', models.TextField()),
                ('bam', models.TextField()),
                ('vcf', models.TextField()),
                ('annotation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('mail', models.TextField()),
                ('name', models.TextField()),
                ('start', models.TextField()),
                ('stop', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CHROM', models.TextField()),
                ('POS', models.TextField()),
                ('REF', models.TextField()),
                ('ALT', models.TextField()),
                ('RS', models.TextField()),
                ('GT', models.TextField()),
                ('GENE', models.TextField()),
                ('DP', models.TextField()),
                ('VARTYPE', models.TextField()),
                ('EFFECT', models.TextField()),
                ('IMPACT', models.TextField()),
                ('HGVS_C', models.TextField()),
                ('PROJECT', models.TextField()),
                ('FILE', models.TextField()),
            ],
        ),
    ]
