# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_results_usermail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJECT', models.TextField()),
                ('FILE', models.TextField()),
                ('USERMAIL', models.TextField()),
            ],
        ),
    ]
