# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-29 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_finishedprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ending',
            field=models.TextField(default=100),
            preserve_default=False,
        ),
    ]
