# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_project_ending'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='readType',
            field=models.TextField(default='pair'),
            preserve_default=False,
        ),
    ]
